print ("Hello, World!")
print ("Meu primeiro exercicio em Python")

print ("Eu sabia que ele ia frear. Ele tem esposa e filhos. Eu, não")
print ("Aonde que o Verstappen vai atacar? Que ponto que ele vai atacar? Porque ele vai atacar!")
print ("Me deixe em paz, eu sei o que estou fazendo!")
print ("BOX, BOX")
print ("Felipe, querido, fique tranquilo")
print ("Não tá bom, não vira, não para, sem tração. Fora isso, tá ótimo")
print ("Sai da p**** do caminho!")
print ("Você me escuta ou não?")
print ("Acabou de acontecer um acidente bem na minha frente.")
print ("...Ok Kimi, houve um acidente no setor um.")
print ("Sim, eu sei, acabei de te dizer!")
print ("wooooohoooooo! Yabadabadeeee! Rrrriiiiiing ding a ding ding ding ding!")
print ("Eu… bem, se você quer que eu… fique doente… terminal… terminalmente doente… então é sushi mesmo!")
print ("Oh, veado! Ha, ha, ha, ha, ha")